name: Nuxt3 CI/CD Demo
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 使用别人封装好的的action，用于clone该仓库的源码到工作流中
      - name: Checkout
        uses: actions/checkout@v3
      # 在工作流中安装node环境（必需，这样才能在后续工作流程中运行 npm install 等指令，否则会报错）
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18 # 指定node版本
      # 打包代码生成环境
      - name: Build
        run: |
          npm install # 安装依赖
          npm run build # 打包前端代码到生产环境
      # 压缩
      - name: Compress build files
        run: |
          tar -czvf build.tar.gz .output # 压缩 .output 目录到 build.tar.gz
      # 部署
      - name: Deploy
        uses: cross-the-world/scp-pipeline@master
        with:
          host: ${{ secrets.HOST }} # 服务器IP（需要在GitHub上自行配置对应的secret）
          user: ${{ secrets.HOST_USER }} # 服务器用户名
          pass: ${{ secrets.HOST_PASS }} # 服务器密码
          connect_timeout: 30s
          local: './.output/*' # 源路径（工作流）
          remote: /home/azureuser # 目标路径（服务器）
          scp: |
            ./*.tar.gz => "/home/azureuser"
      # 在服务器端执行相关指令
      - name: Executing remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }} # 服务器IP（需要在GitHub上自行配置对应的secret）
          username: ${{ secrets.HOST_USER }} # 服务器用户名
          password: ${{ secrets.HOST_PASS }} # 服务器密码
          script: |
            cd /home/azureuser # 进入服务器中的端工程所在的目录
            tar -xzvf build.tar.gz -C ./
            rm build.tar.gz # 确保删除压缩包，节省空间 
            pm2 delete NuxtAppName # 删除旧的进程
            pm2 start ./public/ecosystem.config.js # 启动新的进程
